Add validation
mineiros-io/terraform-google-cloud-function-iam pull request #11
Opened 2022-01-04 03:55 UTC by soerenmartius

- chore: upgrade files from template
- feat: add validation for members
- chore: prepare v0.0.3 release

2022-01-04 16:31 UTC, mariux requested changes

2022-01-04 16:31 UTC, mariux commented on variables.tf
> +    condition     = alltrue([for m in var.members : can(regex("^((allUsers|allAuthenticatedUsers)|(user|serviceAccount|group|domain|projectOwner|projectEditor|projectViewer):(.+))", m))])
```suggestion
    condition     = alltrue([for m in var.members : can(regex("^(allUsers|allAuthenticatedUsers|(user|serviceAccount|group|domain|projectOwner|projectEditor|projectViewer):)", m))])
```

2022-01-04 20:58 UTC, soerenmartius commented on variables.tf
> +    condition     = alltrue([for m in var.members : can(regex("^((allUsers|allAuthenticatedUsers)|(user|serviceAccount|group|domain|projectOwner|projectEditor|projectViewer):(.+))", m))])
resolved in 0424fa0

2022-01-10 00:28 UTC, kassianh approved these changes
lgtm

2022-01-10 09:51 UTC, merged