chore: module tests
mineiros-io/terraform-google-cloud-function-iam pull request #16
Opened 2023-01-13 15:24 UTC by SpecialistSun

- Added computed members support
- Updated docs
- Updated test units

2023-01-13 15:28 UTC, waxb commented on variables.tf
> +    condition     = alltrue([for k, v in var.computed_members_map : can(regex("^(allUsers|allAuthenticatedUsers|(user|serviceAccount|group|domain|principalSet|principal):)", v))])
please update validation condition accordingly to the [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function_iam)

2023-01-13 15:29 UTC, waxb requested changes

2023-01-13 15:29 UTC, waxb commented on variables.tf
> +    condition     = alltrue([for k, v in var.computed_members_map : can(regex("^(allUsers|allAuthenticatedUsers|(user|serviceAccount|group|domain|principalSet|principal):)", v))])
please update validation condition accordingly to the [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function_iam)

2023-01-17 14:08 UTC, switchdk commented on terramate.tm.hcl
> +  name        = "terraform-module-template"
just noticed this. Remember to update the stack `name` and the `description` just below after copying from the template :smile_cat:

2023-01-18 14:39 UTC, waxb requested changes
couple of small things remaining:
- align `outputs.tf` with the example repo
- change pr title to state computed members change
- have three commits: computed members, test update, changelog
- changelog :)

2023-01-18 14:39 UTC, waxb commented on test/unit-minimal/main.tf
>    role = "roles/viewer"
you can remove this as it is optional

2023-01-18 14:39 UTC, waxb commented on test/unit-complete/main.tf
> +module "test" {
please add all arguments to test complete

2023-01-18 14:40 UTC, waxb commented on test/unit-minimal/main.tf
>    role = "roles/viewer"
will discuss with @mariux shortly :)

2023-01-19 12:27 UTC, switchdk commented on test/unit-complete/main.tf
> +  source = "github.com/mineiros-io/terraform-google-service-account?ref=v0.1.0"
```suggestion
  source = "github.com/mineiros-io/terraform-google-service-account?ref=v0.1.1"
```

2023-01-19 12:36 UTC, switchdk commented on README.md
> +  A map of identifiers to identities to be replaced in 'var.members' or in members of `policy_bindings` to handle terraform computed values.
```suggestion
  A map of identifiers to identities to be replaced in `var.members` or in members of `policy_bindings` to handle terraform computed values.
```

2023-01-19 12:37 UTC, switchdk commented on README.tfdoc.hcl
> +             A map of identifiers to identities to be replaced in 'var.members' or in members of `policy_bindings` to handle terraform computed values.
```suggestion
             A map of identifiers to identities to be replaced in `var.members` or in members of `policy_bindings` to handle terraform computed values.
```

2023-01-19 12:37 UTC, switchdk commented on variables.tf
> +  description = "(Optional) A map of members to replace in 'var.members' or in members of 'policy_bindings' to handle terraform computed values."
```suggestion
  description = "(Optional) A map of members to replace in `var.members` or in members of `policy_bindings` to handle terraform computed values."
```

2023-01-19 12:38 UTC, switchdk commented on variables.tf
>    description = "(Optional) The role that should be applied. Only one 'iam_binding' can be used per role. Note that custom roles must be of the format '[projects|organizations]/{parent-name}/roles/{r
```suggestion
  description = "(Optional) The role that should be applied. Only one `iam_binding` can be used per role. Note that custom roles must be of the format `[projects|organizations]/{parent-name}/roles/{role-name}`."
```

2023-01-19 13:00 UTC, switchdk commented on test/unit-complete/main.tf
> +
add `computed_members_map`

2023-01-19 13:08 UTC, switchdk commented on variables.tf
>      error_message = "The value must be a non-empty list of strings where each entry is a valid principal type identified with `allUsers`, `allAuthenticatedUsers` or prefixed with `user:`, `serviceAcc
```suggestion
    error_message = "The value must be a non-empty list of strings where each entry is a valid principal type identified with `allUsers`, `allAuthenticatedUsers` or prefixed with `user:`, `serviceAccount:`, `group:`, `domain:`, `projectOwner:`, `projectEditor:`, `projectViewer:` or  `computed:`."
```

2023-01-20 12:04 UTC, waxb requested changes
please add [terramate manifest](https://github.com/mineiros-io/terraform-module-template/tree/main/.terramate) as well

2023-01-20 12:05 UTC, waxb requested changes
please add [terramate manifest](https://github.com/mineiros-io/terraform-module-template/tree/main/.terramate)

2023-01-20 13:41 UTC, waxb commented
this is a breaking change as support for provider version 3 has been dropped. please put this into the changelog and update the title

2023-01-20 13:47 UTC, waxb requested changes

2023-01-20 13:47 UTC, waxb commented on main.tf
> +  member         = try(var.computed_members_map[regex("^computed:(.*)", each.value)[0]], each.value)
please update the `google_cloudfunctions_function_iam_policy` for computed members as well

2023-01-20 14:39 UTC, waxb requested changes
changelog update is not a breaking commit

2023-01-20 14:39 UTC, waxb commented on CHANGELOG.md
> +- BREAKING: Remove support for Terraform Google Provider versions before v4.0
also terraform version >1 dropped

2023-01-20 15:18 UTC, waxb approved these changes
lgtm

2023-01-21 17:47 UTC, mariux submitted a review, later dismissed
lgtm, good job, thanks.

2023-01-23 10:27 UTC, switchdk commented on variables.tf
> +    condition     = alltrue([for k, v in var.computed_members_map : can(regex("^(allUsers|allAuthenticatedUsers|(llUsers|allAuthenticatedUsers|(user|serviceAccount|group|domain|projectOwner|projectEd
```suggestion
    condition     = alltrue([for k, v in var.computed_members_map : can(regex("^(allUsers|allAuthenticatedUsers|(user|serviceAccount|group|domain|projectOwner|projectEditor|projectViewer):)", v))])
```

2023-01-23 10:31 UTC, switchdk requested changes
Sorry, I missed these changes during my first review. I noticed that a few changes are missing in a few places based on other updated modules. If my notes don't make sense, please just let me know. I wasn't able to comment directly in on the files in Github so I had to make notes like the below instead.

1. `main.tf`, line 20 (`count =`). Comparing to `terraform-google-storage-bucket-iam`, [line 28](https://github.com/mineiros-io/terraform-google-storage-bucket-iam/blob/main/main.tf#L28) 
2. `main.tf`, line 32 (`count =`). Comparing to `terraform-google-storage-bucket-iam`, [line 48](https://github.com/mineiros-io/terraform-google-storage-bucket-iam/blob/main/main.tf#L48) 
3. `main.tf`, line 36 (`policy_data`). Comparing to `terraform-google-storage-bucket-iam`, [line 51](https://github.com/mineiros-io/terraform-google-storage-bucket-iam/blob/main/main.tf#L51) 
4. `main.tf`, line 43 (`count =`), Comparing to `terraform-google-bucket-storage-iam`, [line 57](https://github.com/mineiros-io/terraform-google-storage-bucket-iam/blob/main/main.tf#L57)
5. I think `terramate generate` has not been executed since the unit test folders are missing the `_generated_google.tf` files. If `terramate generate` has been run but the files are not generated then `test/terramate_google.tm.hcl` is probably missing
6. Please update the `test/unit_*_test.go` files. They should contain the three env vars for project, domain and billing account.
7. In `variables.tf`, line 24, the `description` contains single quotes `'` instead of backticks `\``. Please replace with backticks (just like you did in `variable role`
8. In `variables.tf, line 75 and 81. you can remove the `Default is...` in the `description` since it is included in the Terradoc template.

2023-01-24 16:48 UTC, mariux requested changes

2023-01-24 16:48 UTC, mariux commented on main.tf
please use the new local create_policy for count condition here..

2023-01-24 16:48 UTC, mariux commented on main.tf
>    cloud_function = var.cloud_function
please use the new local create_member in for_each condition in this resource

2023-01-24 16:55 UTC, mariux commented
> Sorry, I missed these changes during my first review. I noticed that a few changes are missing in a few places based on other updated modules. If my notes don't make sense, please just let me know. I wasn't able to comment directly in on the files in Github so I had to make notes like the below instead.
> 
>     1. `main.tf`, line 20 (`count =`). Comparing to `terraform-google-storage-bucket-iam`, [line 28](https://github.com/mineiros-io/terraform-google-storage-bucket-iam/blob/main/main.tf#L28)
> 
>     2. `main.tf`, line 32 (`count =`). Comparing to `terraform-google-storage-bucket-iam`, [line 48](https://github.com/mineiros-io/terraform-google-storage-bucket-iam/blob/main/main.tf#L48)
> 
>     3. `main.tf`, line 36 (`policy_data`). Comparing to `terraform-google-storage-bucket-iam`, [line 51](https://github.com/mineiros-io/terraform-google-storage-bucket-iam/blob/main/main.tf#L51)
> 
>     4. `main.tf`, line 43 (`count =`), Comparing to `terraform-google-bucket-storage-iam`, [line 57](https://github.com/mineiros-io/terraform-google-storage-bucket-iam/blob/main/main.tf#L57)

i agree added some notes inline.. please fix those 1-4 topics.

>     7. In `variables.tf`, line 24, the `description` contains single quotes `'` instead of backticks. Please replace with backticks (just like you did in `variable role`

that;s a ice to have, not a blocker though ;) nice catch.

>     8. In `variables.tf`, line 75 and 81. you can remove the `Default is...` in the `description` since it is included in the Terradoc template.

yes, defaults can be omitted... nice catch.. not a blocker...

2023-01-25 13:03 UTC, switchdk approved these changes
Great stuff @SpecialistSun :heart_eyes_cat:

2023-01-30 10:17 UTC, waxb approved these changes
lgtm!

2023-01-31 15:31 UTC, mariux approved these changes
lgtm

2023-01-31 15:31 UTC, merged